FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

# Enable CPU Log and Raw PECI support
EXTRA_OECMAKE_append += "-DBMCWEB_ENABLE_REDFISH_CPU_LOG=ON"
EXTRA_OECMAKE_append += "-DBMCWEB_ENABLE_REDFISH_RAW_PECI=ON"

# Enable Redfish BMC Journal support
EXTRA_OECMAKE_append += "-DBMCWEB_ENABLE_REDFISH_BMC_JOURNAL=ON"
EXTRA_OECMAKE_append += " -DBMCWEB_INSECURE_ENABLE_REDFISH_FW_TFTP_UPDATE=ON"
EXTRA_OECMAKE_append += " -DBMCWEB_HTTP_REQ_BODY_LIMIT_MB=128"
